apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-stack

resources:
  - pvc.yaml
  - deployment.yaml
  # Add sealed-secret.yaml after sealing the secret
  # - sealed-secret.yaml
