apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvidia-license

resources:
  - namespace.yaml
  - deployment.yaml
  # Aggiungi dopo aver creato i certificati:
  # - secret-certs.yaml
