apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-dns

resources:
  - namespace.yaml
  # Uncomment after adding secrets:
  # - ddns-updater/deployment.yaml
  # - cloudflare/deployment.yaml
  # - cloudflare/clusterrole.yaml
  # - windows-dns/deployment.yaml
  # - windows-dns/clusterrole.yaml
