apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media-stack

resources:
  - storageclass.yaml
  - pv-smb.yaml
  - pvc-smb.yaml
  # Add sealed-secret.yaml after sealing
  # - sealed-secret.yaml
